import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    id("java")
    id("maven-publish")
    kotlin("jvm") version "1.3.41"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    testImplementation("junit:junit:4.8.2")
    testImplementation(kotlin("compiler-embeddable"))
}

group = "pl.cdbr"
version = "1.0.0"
description = "A Kotlin conversion of Will Glozer's scrypt for Java."
java.sourceCompatibility = JavaVersion.VERSION_1_8

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "1.8"
    }
}

